src/app.py
from flask import Flask, render_template
from src.common.database import Database

__author__ = 'Yolanda'

app = Flask(__name__)
app.config.from_object('src.config')
app.secret_key = "123"


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.jinja2')


from src.models.users.views import user_blueprint
from src.models.stores.views import store_blueprint
from src.models.alerts.views import alert_blueprint

app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, url_for, redirect

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators

__author__ = 'Yolanda'

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/new', methods=['POST', 'GET'])
@user_decorators.requires_login
# redirect the user to 'users.login' if session['email'] is None
# check the email, if it is not set, redirect to users.login_user; if not, just do create_alert
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()  # This already saves to MongoDB

    return render_template('alerts/new_alert.jinja2')  # Send the user an error if their login was invalid


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])

        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))
    return render_template('alerts/edit_alert.jinja2', alert=alert)


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    return render_template('alerts/alert.jinja2', alert=Alert.find_by_id(alert_id))


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/items/views.py
from flask import Blueprint

__author__ = 'Yolanda'

item_blueprint = Blueprint('items', __name__)

@item_blueprint.route('/item/<string:name>')
def item_page():
    pass

src/models/stores/views.py
from flask import Blueprint, render_template, request, json, redirect, url_for
from src import config
from src.models.stores.store import Store
import src.models.users.decorators as user_decorators

__author__ = 'Yolanda'


store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.jinja2', stores=stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.jinja2', store=Store.get_by_id(store_id), config=config)


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
# @user_decorators.requires_admin_permissions
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()
        return redirect(url_for('.index'))
    return render_template('stores/edit_store.jinja2', store=store)


@store_blueprint.route('/delete/<string:store_id>')
# @user_decorators.requires_admin_permissions
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))


@store_blueprint.route('/new', methods=['GET', 'POST'])
# @user_decorators.requires_admin_permissions
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/new_store.jinja2')

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators

__author__ = 'Yolanda'

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
# GET: give them the data they want (login form)
# POST: website sending us some data. contain an email and a password is we
# want to do something else like save to the database or check that the login in valid.
def login_user():
    if request.method == 'POST':
        # Check login is valid
        email = request.form['email']
        password = request.form['password'] # hashed password

        try:
            if User.is_login_valid(email, password):
                session['email'] = email # temporary storage of data
                # the session for this user is linked to the user via unique ID that is stored in their browser,
                # when the browser arrives or a web page we  give them a unique identifier and they send us the identifier
                # with every request. So we know that the browser is related to this email and flask does all of that work
                return redirect(url_for(".user_alerts"))
                # url_for: get the user in our service for a specific method and that method is the current file user alerts
                # so that is essentially the user profile isn't it
                # redirect: change the address essentially. current url -> another url
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.jinja2") # Send the user an error if their login was invalid


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        # Check login is valid
        email = request.form['email']
        password = request.form['password'] # hashed password

        try:
            if User.register_user(email, password):
                session['email'] = email # temporary storage of data
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2") # Send the user an error if their login was invalid


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    return render_template('users/alerts.jinja2', alerts=user.get_alerts())


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/<string:user_id>')
@user_decorators.requires_login
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Alert
            <small>for '{{ alert.item.name }}'</small>
        </h1>
    </div>
    <p>Last price found <strong>{{ alert.item.price }}</strong></p>
    <p>Last checked on <strong>{{ alert.last_checked.strftime('%d-%m-%Y at %H:%M') }}</strong></p>
    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-default" href="{{ alert.item.url }}" role="button">Visit Site</a>
            <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit
                Alert</a>
            {% if alert.active %}
                <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}"
                   role="button">Deactivate Alert</a>
            {% else %}
                <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}"
                   role="button">Activate Alert</a>
                <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">Permanently
                    Delete alert</a>
            {% endif %}
            <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}"
               role="button">Check alert price</a>
        </div>
    </div>
{% endblock %}

src/templates/alerts/edit_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Alert</h1>
    </div>
    <div class="form-size">
        <form action="/" method="post">
            <div class="form-group">
                <label for="name">Alter/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="{{ alert.item.name }}" disabled>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="{{ alert.item.url }}" disabled>
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="100.0"
                       value="{{ alert.price_limit }}" aria-describedby="priceLimitBlock">
                <span id="priceLimitBlock" class="help-block">We'll send you an e-mail when the price reaches or goes under this.</span>
            </div>
            <button type="submit" class="btn btn-default">Update</button>
        </form>
    </div>
{% endblock %}

src/templates/alerts/new_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Alert</h1>
    </div>
    <div class="form-size">
        <form action="/" method="post">
            <div class="form-group">
                <label for="name">Alter/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="100.0" aria-describedby="priceLimitBlock">
                <span id="priceLimitBlock" class="help-block">We'll send you an e-mail when the price reaches or goes under this.</span>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pricing Service</title>

    {% include 'html_dependencies.jinja2' %}

</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="Home">Pricing</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav" >
                <li><a href="{{ url_for('stores.index') }}">Stores</a></li>
            </ul>
            {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.user_alerts') }}"><span class="glyphicon glyphicon-alert"></span> Your Alerts</a></li>
                    <li><a href="{{ url_for('users.logout_user') }}"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.register_user') }}"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
                    <li><a href="{{ url_for('users.login_user') }}"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-3">Pricing Service</h1>
        <p class="lead">We can online store websites to alert you of price drops in items that interest you.</p>
        <hr class="my-4">
        <p>Just sign up, and get started by adding the URL of an item that you wish to track. We'll do the rest!</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a>
        </p>
    </div>
{% endblock %}

src/templates/html_dependencies.jinja2
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

src/templates/stores/edit_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
    <h1>Edit Store</h1>
    </div>
    <div class="form-size">
    <form method="post">
        <div class="form-group">
            <label for="name">Store name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Store Name" value="{{ store.name }}">
        </div>
        <div class="form-group">
            <label for="url_prefix">Store URL Prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." value="{{ store.url_prefix }}" aria-describedby="storeURLPrefixHelp">
            <span id="storeURLPrefixHelp" class="help-clock">What characters do URLs of all items in this online store start with?</span>
        </div>
        <div class="form-group">
            <label for="tag_name">Tag name</label>
            <input type="text" class="form-control" id="tag_ame" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="storeTagNameHelp">
            <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
        </div>
        <div class="form-group">
            <label for="query">Search Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{"id":"price-now"}' value='{{ store.query | tojson }}' aria-describedby="queryHelpBlock">
            <span id="queryHelpBlock" class="help-block">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation to marks!</span>
        </div>
        <button type="submit" class="btn btn-default">Update</button>
    </form>
    </div>
{% endblock %}

src/templates/stores/new_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Store</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..."
                       aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-clock">What characters do URLs of all items in this online store start with?</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag name</label>
                <input type="text" class="form-control" id="tag_ame" name="tag_name" placeholder="span" value="span"
                       aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query">Search Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id":"price-now"}'
                       value='{"id":"price-now"}' aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation to marks!</span>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Store
            <small>{{ store.name }}</small>
        </h1>
    </div>
    <p>All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
    {% if session['email'] in config.ADMINS %}
        <div class="panel panel-default">
            <div class="panel-body">
                <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit
                    Store</a>
                <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Permanently
                    Delete Store</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

src/templates/stores/store_index.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
    <h1>Stores <small>list of supported stores</small></h1>
    </div>
    <div class="list-group">
        {% for store in stores %}
            <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class="list-group-item">
            <h4 class="list-group-item-title">{{ store.name }}</h4>
                <p class="list-group-item-text">All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p></a>
        {% endfor %}
    </div>
{#    {% if session['email'] in config.ADMINS %}#}
        <a class="btn btn-success" href="{{ url_for('stores.create_store') }}">
        <span class="glyphicon glyphicon-plus"></span> Create new
        </a>
{#    {% endif %}#}
{% endblock %}

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
    <h1>Alerts <small>showing already existing alerts</small></h1>
    </div>
    <div class="list-group">
    {% for alert in alerts %}
        <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}">
            <h4 class="list-group-items-heading">
                {{ '<span class="glyphicon glyphicon-remove-circle"></span>' if not alert.active else '' }} Alert for {{ alert.item.name }}</h4>
            <p class="list-group-item-text">Last price found <strong>{{ alert.item.price }}</strong><br/>
                Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H:%M") }}</strong></p>
        </a>
    {% endfor %}
    </div>
    <a class="btn btn-success" href="{{ url_for('alerts.create_alert') }}"><span class="glyphicon glyphicon-plus"></span> Create new</a>
{% endblock %}

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
            </div>
            <button type="submit" class="btn btn-default">Log in</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.register_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
            </div>
            <button type="submit" class="btn btn-default">Sign up</button>
        </form>
    </div>
{% endblock %}